### ISSUE TITLE
Põhikiri

### ISSUE THREAD

**Issue by tormi** [sauevald/koidu#3]
**[Kaidi Väät](https://www.facebook.com/vkaidi)**'i koostatud draft: https://docs.google.com/document/d/1_41Cmx-ezYOQjUlWVlC0auSeYmoNelcMxSZDCZxW_SE/edit

**Comment by tormi** [comment]
[Investeeringutoetuste korrast](https://www.riigiteataja.ee/akt/411102012104?leiaKehtiv#para4):

>  (1) Toetust on õigus taotleda mittetulundusühingul või sihtasutusel, mis vastab järgmistele tingimustele:
>   2) taotleja põhikirjast tulenev tegevuse eesmärk on aleviku, küla või muu tervikliku piirkonna elukeskkonna arendamine ning avalikkuse kaasamisele ja avaliku huvi realiseerimisele suunatud tegevus;

**Comment by alanluuk** [comment]
Põhikirja 7.4 ja 7.5 vajaksid vist veidi ümbersõnastamist. Vähemalt esmapilgul tundus mitmetimõistetav (eesmärgi muutmine on ka põhikirja muutmine)

**Comment by tormi** [comment]
Viiks need ühe punkti alla, 2/3 häältega?

EDIT: 
Jätaks 7.4 ära, sest 7.5 katab selle ära?

> 7.4. Seltsi eesmärgi muutmiseks on vajalik 9/10 üldkoosolekul osalenud liikmete häältest.
> 7.5. Seltsi põhikirja muutmiseks ja seltsi tegevuse lõpetamiseks on vajalik üldkoosoleku 2/3 häälteenamus.

**Comment by tormi** [comment]
Võtsin 7.4 maha. Sulgen kande, tundub valmis olevat.

**Comment by tormi** [comment]
> **[Rauno Tuul](https://www.facebook.com/groups/koidu/permalink/1437814549595457/?comment_id=1439896766053902&reply_comment_id=1444390785604500)** 
> Soovitaksin põhikirjas sõnastada pikemalt lahti asutajaliikmete, juhatuse liikmete ja lihtliikmete seose äriregistriga. Väga lihtne on arvata kedagi sooviavalduse alusel kedagi külaseltsist välja, kuid äriregistriga nii lihtsalt ei käi...
> Kas äriregistrisse kantakse asutajaliikmed või valitav juhatus?
> Lisaks tuleks selgemini määratleda juhatuse õigused/volitused/vastutused - äriregistrisse kantud isikud vastutavad MTÜs toimuva eest kogu enda maise varaga. Alati on oht, et juhtub midagi ebaviisakat alla 10000€ ja üldkoosoleku piiri.
> Ma olen olnud ühes MTÜs ning selle likvideerimine (kaasa arvatud selle B-kaardi pealt minema saamine) oli paras ettevõtmine. Võrreldes MTÜ likvideerimisega on asutamine kukepea.
> Ma isiklikult toetan MTÜ initsiatiivi, aga paraku ma enda isikukoodi äriregistrist leida ei soovi.

**Comment by tormi** [comment]
> **[Ave Kruus](https://www.facebook.com/ave.kruus)**
> peate selgeks tegema kes on liikmed- nö lihtliikmed, kes on juhatuse liikmed- allkirja õiguslikud isikud ja vastutajad
> kõik asutajaliikmed ei pea olema juhatuse liikmed- ise soovitan pigem hoida lihtsat joont 1-2 juhatuse liiget on täiesti piisav
> kui soovite et igal aastal vahetub siis valige lühema tähtaja, seaduse järgi on juh. liikme volitused kehtivad 3 aastat
> paras jama on kui on 10 juh liiget nt kasvõi majandusaasta aruande allkirjastamine jms
> lisaks peate kindlast põhikirja märkima seadusega säetastatud punktid mis hiljem on teil vajalikud nt projektirahastuse küsimuseks
[Ääsmäe seltsi põhikiri.pdf](https://github.com/sauevald/koidu/files/1058034/Aasmae.pohikiri.pdf)

**Comment by tormi** [comment]
> **[Maido Reinmann](https://www.facebook.com/maido.reinmann)**
> Ma olen Avega nõus.Kui juhatus on liiga suur,siis läheb lappama.Ja juhatuse valimised peaksid toimuma 2a.tagant
> See Ave kirjutatud 3a.ma pean uurima,kuna minu teada 2apeaks samuti lubatud olema
> 1a.ei pruugi mingit projekti kui me taotleme,lõpuni viia,kuna asjad meie riigis venivad alates sellest et mingi taotluse esitamisel eraldatakse mingid rahad alles tuleval aastal jne. Kui juh.peaks vahepeal muutuma,siis võib kõik ventikasse lennata

**Comment by tormi** [comment]
[**Kati Oolo**](https://www.facebook.com/kati.oolo) täiendas: https://docs.google.com/document/d/1Ra64prweTTCA1Dfxc6WDw8c8XyMTMBcBWbIe8nwOxRQ/edit

> Nii sai nüüd korralikult pusitud
> MTÜ Koidu Külaselts põhikiri.docx
> Mõned mõtted: ühe koha tegin punaseks ja siin mõtte koht, et kas paneme summalise piirangu, milliseid kandeid võib teha juhatus ja mida üldkoosoleku otsus
> mõtlen et kui iga projekti elluviimiseks ja summa ülekandmiseks vaja üldkoosolek kokku kutsuda võib bürokraatiat palju olla
> küsimus on ilmselt selles, kuivõrd me juhatust usaldama
> Veel mõtteid: Ääsmäel on aetud asi üsna keeruliseks salajased hääletused jms ... ma isiklikult arvan, et esialgu võiks jääda võimalikult lihtsaks ja ehk suudame ilma salajaste asjadeta organid valida
> seega jätsin lihtsad variandid
> praegu ei lisanud ka juhatuse tagasikutsumise punkte, aga vbl ikkagi peaks ?

**Comment by tormi** [comment]
> mõtlen et kui iga projekti elluviimiseks ja summa ülekandmiseks vaja üldkoosolek kokku kutsuda võib bürokraatiat palju olla

Nõus. @alanluuk, mida endise MTÜ-tajana arvad?

> esialgu võiks jääda võimalikult lihtsaks ja ehk suudame ilma salajaste asjadeta organid valida
seega jätsin lihtsad variandid

:+1: 

> praegu ei lisanud ka juhatuse tagasikutsumise punkte, aga vbl ikkagi peaks ?

Selline võimalus peaks põhimääruses olema.

**Comment by tormi** [comment]
Äriregistrile esitatud versioon: [Koidu Külaseltsi põhikiri.pdf](https://github.com/sauevald/koidu/files/1116977/Koidu.Kulaseltsi.pohikiri.pdf)
