### ISSUE TITLE
Pargi ja mänguväljaku kinnistute kasutusleping seltsi ja valla vahel

### ISSUE THREAD

**Issue by tormi** [sauevald/koidu#66]
## Idee

Sõlmida pargi (#11) ja mänguväljaku (#8) kinnistute kasutusleping seltsi ja valla vahel. On eelduseks toetuste taotlemisele.

- [x] 12.07.2017 [Külaseltsi taotlus](https://github.com/sauevald/koidu/issues/66#issuecomment-314749413)
- [x] 31.08.2017 Vallavolikogu otsus
- [x] 20.09.2017 Lepingu sõlmimine

**Comment by tormi** [comment]
Läheb volikogu augustikuu päevakorda.

**Comment by tormi** [comment]
Kati abiga:
- [Otsuse-eelnõu_Koidu-tee-7a-ja-Koidu-tee-1-kinnistute-tasuta-kasutusse-andmine_MTÜ-Koidu-Külaselts.docx](https://github.com/sauevald/koidu/files/1141825/Otsuse-eelnou_Koidu-tee-7a-ja-Koidu-tee-1-kinnistute-tasuta-kasutusse-andmine_MTU-Koidu-Kulaselts.docx)

**Comment by tormi** [comment]
Otsuse aluseks soovis vald taotlust, koostasin:

> Koidu Külaselts MTÜ <koidu.kylaselts@gmail.com> | 12. juuli 2017 15:04
> Saaja: info@sauevald.ee
> Koopia: kalle.pungas@sauevald.ee
> 
> Tere.
> 
> Edastan Koidu Külaselts MTÜ taotluse.
> 
> Tervitades,
> Tormi Tabor
> Juhatuse liige
> Koidu Külaselts MTÜ
> - [Sotsiaalmaade kasutuslepingu taotlus.pdf](https://github.com/sauevald/koidu/files/1141887/Sotsiaalmaade.kasutuslepingu.taotlus.pdf)

https://docs.google.com/document/d/12GClODyDdWqWyNsjxoIDfwGDU4mhLBQ8mCoQGY5uqVE/edit#

**Comment by rainvaat** [comment]
Väga hea, nõus

**Comment by tormi** [comment]
20.09.2017 allkirjastasin lepingu seltsi poolt, https://drive.google.com/open?id=0B7L2hwb4QY2UUXNOTkVFbDFScFE
