### ISSUE TITLE
Juhatuse koosolek 17.07.2017

### ISSUE THREAD

**Issue by tormi** [sauevald/koidu#75]
## Päevakorra projekt

1. **Juhatuse esimehe valimine** 
Põhikirja p. 7.1 järgi valib juhatus enda seast esimehe.

Ettepanek: valida esimeheks ...

2. **Moodustatavale tennisekompleksi kinnistule seltsi kasuks hoonestusõiguse seadmise taotlus**
Vallaga konsulteerides jõuti järeldusele (#62), et kõige mõistlikum oleks järgmine skeem:
    - kinnistu omanik Saue vald
    - hoonestusõiguse omanik Koidu Külaselts MTÜ
    - operaator rendilepingu alusel Laagri Tennisekool MTÜ (ja vajadusel teised huvilised).

Ettepanek: Esitada hoonestusõiguse seadmise taotlus vastavalt https://github.com/sauevald/koidu/issues/62#issuecomment-315207181

3. **Tennisekompleksi projektirühm**
Tennisekompleksi rajamiseks (sh detailplaneeringu, ehitusprojekti koostamine jne) tuleks moodustada senisest laiem projektirühm, et kaasata asjast huvitatud kompetentseid külaelanikke.

Ettepanek: teha külaelanikele vastav ettepanek.

4. **Maaküttetorustiku paigaldus**
Tulevase hoone (#16) tarvis oleks mõistlik enne killustikaluse rajamist paigaldada tulevaste tenniseplatside alla maaküttetorustik (#73).

Ettepanek: leida finantseerimise võimalus, sest hiljem on torustiku paigaldamine võimatu.

5. **Pangakonto avamine**
Seltsile tuleb avada pangakonto, valime panga (#34).

Ettepanek: LHV kui kõige soodsam?

6. **Seltsi liikmeks astumise avaldused**
Põhikirja p. 3.3 järgi otsustab juhatus seltsi liikmeks vastuvõtmise lihthäälteenamusega. Avaldused:
    - Anti Leedu

Ettepanek: kinnitada seltsi liikmeks

7. **Infopunktid**
    - Koidu pargi ja mänguväljaku kinnistute otsustuskorras tasuta kasutamise taotlus (#66)
    - Padula jaama graafiku tihendamise taotlus (#32)
    - Karutiigi asumi kuuluvuse hääletus (#76)

Ettepanek: võtta teadmiseks

**Comment by rainvaat** [comment]
1. Teen ettepaneku valida juhatajaks Tormi Tabor
2. Moodustatavale tennisekompleksi kinnistule seltsi kasuks hoonestusõiguse seadmise taotlus - viia läbi vastavalt Tormi poolt ette valmistatud dokumentidele
3. Mul puudub kompetents selles küsimuses kaasa rääkida, olen juhatuse ülejäänud liikmete arvamusega nõus
4. Kui see on vajalik ning ei põhjusta külaseltsile kulusid, s.t. on võimalik leida finantseering, siis nõus
5. LHV kui odavaim on ilmselt mõistlik
6. Nõus
7. Võetud teadmiseks

**Comment by tormi** [comment]
> 4. Kui see on vajalik ning ei põhjusta külaseltsile kulusid, s.t. on võimalik leida finantseering, siis nõus

Eks me eelkõige juhatusena peamegi seda hindama. Kui me soovime sinna köetava hoone püstitada, tuleb   mõelda küttelahenduse peale. Toru vedamine õigesse kohta praegu on oluliselt odavam, kui hiljem mingi muu variant.

Mõtlesin, et peaksime algatama sponsorite leidmise kampaania. Hetkel on meil üks perekond Leedu näol olemas, aga nad on juba praegu väga palju panustamas (krunt, tee/parkla, platside killustikalused jne).

Sponsorobjektid võiks 1. etapis olla:

1. maa-alune infra (projekt, elekter, maaküttetorustik, veetorustik+puurkaev, reoveelahendus)
2. väljaku 1 pealisehitus (purukate, aed, võrk jms)
3. väljaku 2 pealisehitus
4. väljaku 3 pealisehitus
5. väljaku 4 pealisehitus

Sponsoritele saaksime vastu pakkuda näiteks nimelisi väljakuid.

**Comment by tormi** [comment]
Lihtsam on vist nii, et ongi 4 sponsorobjekti - 4 nimelist väljakut (#12) ja sponsorid katavad võrdses osas kõik 1. etapi (väljakud + p. 1 infra) ülejäänud kulud. Need peaks jääma ca 30 tuh. euro suurusjärku väljaku kohta (täpsem eelarve on alles koostamisel). 2. etapis teeme olmehoone (#16).

**Comment by alanluuk** [comment]
Väljakute tagustele tuuletõkkepindadele saab paigaldada sponsorreklaamid. Rääkisin sellest täna Oskariga leidsime mõistliku pakkumise millega minna soojupumbafirmadele reklaamipinda pakkuma vastutasuks nendepoolsele maakontuuri paigaldamisele. 
Asja paremaks sujumiseks peaksime kokku panema koidu tenniseväljakuid tutvustava lehe.

**Comment by tormi** [comment]
> Väljakute tagustele tuuletõkkepindadele saab paigaldada sponsorreklaamid.

Eelkõige neid pindasid pidasingi silmas nimeliste väljakute idee juures. Siin peab korra mõtlema, milline variant on pikemas vaates mõistlik - kas iga toru kohta plakat või 1 väljak = 1 suursponsor. Tahaks Raini ja Oskari arvamust siin.

**Comment by tormi** [comment]
> Asja paremaks sujumiseks peaksime kokku panema koidu tenniseväljakuid tutvustava lehe.

Onepager või sobib ka https://medium.com/koidu/koidu-tennisev%C3%A4ljakud-cf44e93067cb stiilis artikkel?

**Comment by tormi** [comment]
Saabus ka Allar Leedu sisend:
![screenshot from 2017-07-20 09-43-38](https://user-images.githubusercontent.com/146800/28403976-f44530ec-6d2f-11e7-8738-bcda57fa2c2d.png)

**Comment by tormi** [comment]
Protokoll: https://docs.google.com/document/d/138M5qNE6SQ-L4Piue_4nrf09L9p8-OvFH2v7YBivkCE/edit?usp=sharing
- [20170720-Koidu-Külaseltsi-juhatuse-koosoleku-protokoll.pdf](https://github.com/sauevald/koidu/files/1166849/20170720-Koidu-Kulaseltsi-juhatuse-koosoleku-protokoll.pdf)

**Comment by alanluuk** [comment]
arvan, et see onepager sobib alguseks ka.
Kas meil on juba sponsorluse kohalt tekkinud mingi strateegiline arusaamine?
Väljakutealustest kommunikatsioonidest rääkides tuleb meil ilmselt tregemist teha:
1. maakütte välistorustikuga.
1. veetorud väljakute kastmiseks.
1. väljakute drenaaž.
1. kaablikõrid perspektiivis väljakute valgustuse väljaarendamiseks

Täiendage/parandage

Väljakute kastmise torustik vajab täpset väljakute plaani. Edasine võiks olla suhtkoht lihtne ja odav.

Drenaaži kohalt peaks kindlasti ekspertidelt nõu küsima.

Perspektiivse valguslahendusega sama lugu. Kõrid + vedamine on suhtkoht lihtne ja odav.

Maaküttekontuuri toru meetri hind on jaes ca 1EUR/meeter. 300m2 hoone kütmiseks peaks arvestama 1000-2000 meetrise korntturiga (olenevalt pinnase niiskusest). Ekspert peab ütlema mitu paralleelset ringi peab tegema (kogu kontuur ühe toruna tõenäoliselt ei lähe sest hakkab oma latentsiga kompressorit koormama).

Soojuspumba firmade huvi näen eelkõige selles, et olles neilt juba saanud kontuuri ostaksime neilt tõenäoliselt hiljem ka pumba ja hooldust. Pakutav reklaampind oleks siinjuures vahend siduvatest (pumbaostu vms)lepingutest hoidumiseks.

**Comment by tormi** [comment]
@alanluuk, kolime #73 -e üle, ma tahan selle sulgeda.

**Comment by tormi** [comment]
> Kas meil on juba sponsorluse kohalt tekkinud mingi strateegiline arusaamine?

Siin pole arenguid olnud, tuleb otsida sponsoreid ja taotleda toetusi. Olen jätkuvalt seda meelt, et suursponsorite äramärkimiseks on hea kasutada nimelisi väljakuid. Lisaks võiks saada teha annetusi, iga annetaja märgitaks nimetahvlil ära, a'la Pärimusmuusika ait:
![nimetahvel_7_20140320_1949911444](https://user-images.githubusercontent.com/146800/28485238-d0f24be6-6e80-11e7-8a69-2b314ad38ba6.jpg)

**Comment by tormi** [comment]
@alanluuk ,

> arvan, et see onepager sobib alguseks ka.
> Kas meil on juba sponsorluse kohalt tekkinud mingi strateegiline arusaamine?

Nende teemadega siin edasi: #80
