### ISSUE TITLE
Trossrada / ahviraudtee

### ISSUE THREAD

**Issue by tormi** [sauevald/koidu#9]
## Idee

Laste üheks lemmikuks on ahviraudtee / zipline / trossrada. Lisaks võtmed-kätte lahendusele uurime ise tegemise võimalusi.

### Asukoht

![20689959_10203470786007578_5375162857310911620_o](https://user-images.githubusercontent.com/146800/29288408-4937428c-8141-11e7-8f23-3b4f7537ad0e.jpg)

### Ehitamiseks vajaminevad detailid ja eelarve
- https://docs.google.com/spreadsheets/d/1AJlpsgWfIqz4T46HG3Q1F1BvoRfFX--zTkIWQ9XY66w/edit#gid=548994431

**Comment by tormi** [comment]
Lisasin otse LÜ-sse.

**Comment by tormi** [comment]
![screenshot from 2017-08-15 16-57-18](https://user-images.githubusercontent.com/146800/29318996-fd624b00-81da-11e7-93b2-2309a7fccc9b.png)

**Comment by tormi** [comment]
## HAMMERJACK

[Trossid, ketid ja nende tarvikud](https://hammerjack.eu/index.php?route=product/category&path=1_9_916)

- [x] CABLE - [Tross 10mm (7x19) A4 /happekindel](https://hammerjack.eu/index.php?route=product/product&product_id=21881)
- [x] CABLE CLAMPS - [Trossilukk 10mm Zn DIN 741](https://hammerjack.eu/index.php?route=product/product&product_id=2596)
- [ ] TURNBUCKLE - [Trossipinguti DIN 1480 A4 10mm k.konks - k.konks Happekindel](https://hammerjack.eu/index.php?route=product/product&product_id=21880) - joonisel on kahvelotstega, HJ-s "kinnine konks". Paneme [seekli](https://hammerjack.eu/index.php?route=product/product&path=1_9_916_91607&product_id=2671) abil sobima.
- [ ] CABLE SLING
- [ ] THIMBLE - [Kouss DIN 6899 10mm](https://hammerjack.eu/index.php?route=product/product&path=1_9_916_91606&product_id=2630)
- [ ] BRAKE BLOCK

![screenshot from 2017-08-15 16-50-26](https://user-images.githubusercontent.com/146800/29318695-dcd4e42a-81d9-11e7-80c7-e8bacb63b984.png)

**Comment by tormi** [comment]
Käisin Saue seikluspargis vaatamas, seal on hoopis lihtne konstruktsioon:

![20170815_202451](https://user-images.githubusercontent.com/146800/29329903-19e4f62c-8200-11e7-9650-93fd1aefbbf8.jpg)
![20170815_202503](https://user-images.githubusercontent.com/146800/29329966-476ee292-8200-11e7-996b-836ccdc8948a.jpg)
![20170815_202610](https://user-images.githubusercontent.com/146800/29329983-5bd01d46-8200-11e7-9658-863002e97a00.jpg)

Minu sealoleku ajal oli trossrada ainuke atraktsioon, kus oli kogu aeg saba. Raja pikkus on umbes sama nagu meie kavandatav:
![20170815_202618](https://user-images.githubusercontent.com/146800/29330039-90a112dc-8200-11e7-945b-b00aa1fea213.jpg)

Stopper:
![20170815_202634](https://user-images.githubusercontent.com/146800/29330126-e8f15078-8200-11e7-8d29-72df61b61cec.jpg)

Pukk:
![20170815_202508](https://user-images.githubusercontent.com/146800/29333591-fe1aff42-820c-11e7-9d27-3f5e7646412a.jpg)

**Comment by tormi** [comment]
Trossraja iste on sama konstruktsiooniga - veekindlast vineerist ketas köie otsas:
![20170815_202733](https://user-images.githubusercontent.com/146800/29330167-05a9c150-8201-11e7-815e-cc336baa20e8.jpg)

**Comment by tormi** [comment]
[Ääsmäe seikluspargi](http://aasmae.weebly.com/aumlaumlsmaumle-seikluspark.html) ehitaja: https://www.facebook.com/3park.adventure/

**Comment by raunz** [comment]
Kas trossi/pingutite materjalina happekindel A4 liialdus pole? Korralik tsingitud tross kestab ka kasutades kaua...
Trosside/rihmade osas on ülemiste city's tegutsev ettevõte, keda omast kogemusest soovitaksin:
http://www.mazam.eu/tooted/terastross-kraana-tross-vintsi-tross/
Trossi alumises otsas võiks pidurina kasutada vedru (nagu Laagris redise tänava mänguväljakul (seal on ka väga hea iste)).
Kõige rohkem leiutamist on ilmselt pukiga, kus vaja lihtsalt osavat puutööd teha.

**Comment by tormi** [comment]
Tere @raunz ;)

> Kas trossi/pingutite materjalina happekindel A4 liialdus pole? 

Ilmselt ongi. Ma valisin praegu selle järgi, milline toode oli märgitud kasutamiseks välistingimustes. Aga Sauel tundub olevat ka tavaline tsingitud tross.

**Comment by tormi** [comment]
Uus eelarve: https://docs.google.com/spreadsheets/d/1AJlpsgWfIqz4T46HG3Q1F1BvoRfFX--zTkIWQ9XY66w/edit#gid=548994431

**Comment by tormi** [comment]
## AVAMAA trossrada

Esimene ots, trossi läbimõõt 10 mm
![20170818_123636](https://user-images.githubusercontent.com/146800/29461191-77729a6c-8433-11e7-96a9-37a00bf3496d.jpg)

Tagumine ots, puks+ vedru
![20170818_123809](https://user-images.githubusercontent.com/146800/29461253-b2d38c10-8433-11e7-84f2-125bcf4a8599.jpg)
![20170818_123802](https://user-images.githubusercontent.com/146800/29461237-a0088f86-8433-11e7-99c5-c79b23995f61.jpg)

**Comment by tormi** [comment]
Puki materjalid:
- keermelatt 0.5m, lm 12?, 4 tk
- mutrid, 4 tk
- seibid, 4 tk
- kübarmutrid või plastkaitsmed, 4tk
- immutatud poolitatud aiapostid, lm 80, s 700, 8 tk
- imm. 70x120? prussid s 1000, 4 tk
- imm. lauad 8 jm
- 60x60 vinklid, 4 tk
- kruvid 120, 10 tk
- puupakk

**Comment by tormi** [comment]
Lisaks trepp

**Comment by tormi** [comment]
Tehtud.

Eelarve: https://docs.google.com/spreadsheets/d/1AJlpsgWfIqz4T46HG3Q1F1BvoRfFX--zTkIWQ9XY66w/edit#gid=548994431
![trossrada](https://user-images.githubusercontent.com/146800/30791784-af686698-a1bd-11e7-9019-d72f3f892be6.jpg)
